//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8830
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="PTTInfoSoap", Namespace="http://www.pttplc.com/ptt_webservice/")]
public partial class PTTInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CurrentOilPriceOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetOilPriceOperationCompleted;
    
    /// <remarks/>
    public PTTInfo() {
        this.Url = "http://www.pttplc.com/webservice/pttinfo.asmx";
    }
    
    /// <remarks/>
    public event CurrentOilPriceCompletedEventHandler CurrentOilPriceCompleted;
    
    /// <remarks/>
    public event GetOilPriceCompletedEventHandler GetOilPriceCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pttplc.com/ptt_webservice/CurrentOilPrice", RequestNamespace="http://www.pttplc.com/ptt_webservice/", ResponseNamespace="http://www.pttplc.com/ptt_webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CurrentOilPrice(string Language) {
        object[] results = this.Invoke("CurrentOilPrice", new object[] {
                    Language});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCurrentOilPrice(string Language, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CurrentOilPrice", new object[] {
                    Language}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndCurrentOilPrice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void CurrentOilPriceAsync(string Language) {
        this.CurrentOilPriceAsync(Language, null);
    }
    
    /// <remarks/>
    public void CurrentOilPriceAsync(string Language, object userState) {
        if ((this.CurrentOilPriceOperationCompleted == null)) {
            this.CurrentOilPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCurrentOilPriceOperationCompleted);
        }
        this.InvokeAsync("CurrentOilPrice", new object[] {
                    Language}, this.CurrentOilPriceOperationCompleted, userState);
    }
    
    private void OnCurrentOilPriceOperationCompleted(object arg) {
        if ((this.CurrentOilPriceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CurrentOilPriceCompleted(this, new CurrentOilPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pttplc.com/ptt_webservice/GetOilPrice", RequestNamespace="http://www.pttplc.com/ptt_webservice/", ResponseNamespace="http://www.pttplc.com/ptt_webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetOilPrice(string Language, short DD, short MM, short YYYY) {
        object[] results = this.Invoke("GetOilPrice", new object[] {
                    Language,
                    DD,
                    MM,
                    YYYY});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetOilPrice(string Language, short DD, short MM, short YYYY, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetOilPrice", new object[] {
                    Language,
                    DD,
                    MM,
                    YYYY}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetOilPrice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetOilPriceAsync(string Language, short DD, short MM, short YYYY) {
        this.GetOilPriceAsync(Language, DD, MM, YYYY, null);
    }
    
    /// <remarks/>
    public void GetOilPriceAsync(string Language, short DD, short MM, short YYYY, object userState) {
        if ((this.GetOilPriceOperationCompleted == null)) {
            this.GetOilPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOilPriceOperationCompleted);
        }
        this.InvokeAsync("GetOilPrice", new object[] {
                    Language,
                    DD,
                    MM,
                    YYYY}, this.GetOilPriceOperationCompleted, userState);
    }
    
    private void OnGetOilPriceOperationCompleted(object arg) {
        if ((this.GetOilPriceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetOilPriceCompleted(this, new GetOilPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void CurrentOilPriceCompletedEventHandler(object sender, CurrentOilPriceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CurrentOilPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CurrentOilPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetOilPriceCompletedEventHandler(object sender, GetOilPriceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetOilPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetOilPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
